### ISSUE TITLE
Point's list in SAM

### ISSUE THREAD

**Issue by BroKis** [Z-Zheng/pytorch-change-models#2]
@Z-Zheng, Hi. Is there any guide or description of points in points_match methods to select specific classes? Thanks

**Comment by Z-Zheng** [comment]
Thank you for your feedback! You could check [point query case](https://github.com/Z-Zheng/pytorch-change-models/blob/main/torchange/models/segment_any_change/README.md#case-2-point-query-mode-segment-change-of-interest).
